### ISSUE TITLE
Does not work properly with current minetest-dev

### ISSUE THREAD

**Issue by VanessaE** [Rogier-5/minetest-mapper-cpp#19]
The mapper returns tons and tons of errors of this nature:

```
Coordinates: -1120,16,-1552+16+16+16;  Cause: incorrect header check
Failed to decompress data in map block -70,0,-97 (id: -1627390022). Block corrupt ?
Coordinates: -1120,0,-1552+16+16+16;  Cause: incorrect header check
Failed to decompress data in map block -69,2,-97 (id: -1627381829). Block corrupt ?
Coordinates: -1104,32,-1552+16+16+16;  Cause: incorrect header check
Failed to decompress data in map block -69,1,-97 (id: -1627385925). Block corrupt ?
Coordinates: -1104,16,-1552+16+16+16;  Cause: incorrect header check
Exception: Too many block unpacking errors - bailing out
```

And it creates weirdly-sized/stretched/scaled images.

When I asked about this in #minetest-dev, I was told that the mapper needs "some changes" to work with current Minetest engine code.  According to @sfan5, this commit is what led to the errors, https://github.com/minetest/minetest/commit/f17c9c45dc30a388675d46418d278a4a029206e2, and this fixes it in upstream mapper, https://github.com/minetest/minetestmapper/commit/21444d00c35dc6896ffc27af7da38d8a296178fd.

Making an equivalent change to your fork seems to fix the problem.  Also, it would be a good idea to print the path to map.db (or map.sqlite) when throwing any kind of error.  I run several mapper instances at once, each on a different world (to take advantage of multiple cores), and when an error happens, I can't tell which world it came from.

**Comment by enkidu-smith** [comment]
Probably related to [this](https://forum.minetest.net/viewtopic.php?f=18&t=16657)?

**Comment by fireglow** [comment]
Seeing that issue, too.

**Comment by LazyJ** [comment]
I've tested adrido's PR #20 with LinuxGaming's MT 0.4.14 _(18gb world file)_ and MT 0.5.0-dev _(1gb world file)_ and it works well with both.

I've been using Rogier-5's version of minetestmapper-cpp for several years now. His version has more features and has **not** been as problematic for me as the Minetest "official" version has during those same years.

So Rogier-5, if you happen to read this, please know that there are still folks who prefer to use your mapper and we sure would appreciate you keeping it maintained. Thanks ;)
