### ISSUE TITLE
--drawalpha does not generate correct results

### ISSUE THREAD

**Issue by VanessaE** [Rogier-5/minetest-mapper-cpp#6]
Here's what upstream minetestmapper does:

![image](https://cloud.githubusercontent.com/assets/1733537/10298147/048cee48-6ba9-11e5-92cf-034cada7a457.png)

Whereas your fork results in this:

![image](https://cloud.githubusercontent.com/assets/1733537/10298125/dad3a182-6ba8-11e5-92b5-49954108562e.png)

The second image is a screenshot taken from a Leaftest-generated interactive map page, which can be found here:  http://digitalaudioconcepts.com/vanessa/hobbies/minetest/worldmaps/FreeForAll_World/map.html .  For easier comparison, both images have been cropped to the same world position and image dimensions, down to the pixel.

The colors.txt file used to generate these images is here:

http://digitalaudioconcepts.com/vanessa/hobbies/minetest/colors.txt

**Comment by Rogier-5** [comment]
My version of minetestmapper uses a different drawalpha algorithm by default. Your map should look more similar to the one from upstream minetestmapper when using --drawalpha=cumulative.

The difference is that using upstream minetestmapper, water will become opaque after a certain depth (iirc, beyond a depth of 10 there will no longer be much transparency left). In my version, using plain --drawalpha (same as --drawalpha=average), the first opaque node always shines through the stack of transparent nodes above it. Any under-water builds are therefore always visible.

Note: when using --drawalpha, I recommend using darker water colors, in particular when using the 'average' algorithm. See [drawalpha](https://github.com/Rogier-5/minetest-mapper-cpp/blob/master/doc/manual.rst#drawalpha-cumulative-cumulative-darken-average-none). In case you're not aware: a way to achieve this while keeping the existing colors file as is, is to use create a new (empty) colors file, add a line `@include /path/to/colors.txt`, and after it, add lines redefining just the water colors. See [colors common syntax](https://github.com/Rogier-5/minetest-mapper-cpp/blob/master/doc/manual.rst#colors-files-common-syntax). Also note that my version of minetestmapper accepts different (distinct) colors for opaque and non-opaque water in the same colors file, see [colors.txt syntax](https://github.com/Rogier-5/minetest-mapper-cpp/blob/master/doc/manual.rst#colorstxt-syntax).

**Comment by VanessaE** [comment]
Ah, cumulative mode is indeed what I was looking for.  Thanks!

Note to self:  read the documentation more thoroughly. :smile:
